const STORAGE_KEY="dashgpt.demo.results.v1";
const seedResults=[{id:"dashgpt-product",title:"DashGPT product concept",summary:"A private dashboard for useful AI outcomes and portable working context across chats and agents.",category:"DashGPT",tags:["product","context","privacy"],favorite:true,decisions:["Result-first, not chat-first","Private by default","Local-first and cloud-optional"],next:"Prove the first local Result → Context Pack loop."},{id:"development-workflow",title:"Provider-agnostic development workflow",summary:"Specs and durable project state live in the repository so Claude, Codex, Copilot, OpenCode or local models can take over.",category:"Development",tags:["openspec","agents","sdd"],favorite:true,decisions:["OpenSpec starts as the SDD framework","AGENTS.md stays short","Agents are replaceable"],next:"Create and review M1 as a vertical slice."},{id:"deployment",title:"Fast private deployment",summary:"Target experience: GitHub + Cloudflare accounts → guided setup → a protected personal DashGPT instance.",category:"Deployment",tags:["cloudflare","github","self-hosted"],favorite:false,decisions:["Cloud is a deployment target, not a core dependency","Self-hosting remains supported"],next:"Connect Cloudflare after the first demo works locally."}];
let results=loadResults();let activeCategory="All";let favoritesOnly=false;
const resultsGrid=document.querySelector("#resultsGrid"),resultCount=document.querySelector("#resultCount"),resultsTitle=document.querySelector("#resultsTitle"),emptyState=document.querySelector("#emptyState"),searchInput=document.querySelector("#searchInput"),categoryFilters=document.querySelector("#categoryFilters"),cardTemplate=document.querySelector("#resultCardTemplate"),resultDialog=document.querySelector("#resultDialog"),resultDialogContent=document.querySelector("#resultDialogContent"),contextDialog=document.querySelector("#contextDialog"),contextOutput=document.querySelector("#contextOutput"),addDialog=document.querySelector("#addDialog"),addResultForm=document.querySelector("#addResultForm");
function loadResults(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(parsed)&&parsed.length?parsed:structuredClone(seedResults)}catch{return structuredClone(seedResults)}}
function saveResults(){localStorage.setItem(STORAGE_KEY,JSON.stringify(results));updateSummary()}
function updateSummary(){const favorites=results.filter(r=>r.favorite).length;document.querySelector("#summaryText").textContent=`${results.length} results, ${favorites} favorites. Search, open a result, or generate a portable Context Pack.`}
function categories(){return["All",...new Set(results.map(r=>r.category).filter(Boolean))]}
function renderCategoryFilters(){categoryFilters.replaceChildren();categories().forEach(category=>{const button=document.createElement("button");button.className=`chip${activeCategory===category?" active":""}`;button.type="button";button.textContent=category;button.addEventListener("click",()=>{activeCategory=category;render()});categoryFilters.appendChild(button)})}
function filteredResults(){const query=searchInput.value.trim().toLowerCase();return results.filter(result=>{const categoryMatch=activeCategory==="All"||result.category===activeCategory;const favoriteMatch=!favoritesOnly||result.favorite;const haystack=[result.title,result.summary,result.category,...(result.tags||[]),...(result.decisions||[]),result.next].filter(Boolean).join(" ").toLowerCase();return categoryMatch&&favoriteMatch&&(!query||haystack.includes(query))})}
function render(){renderCategoryFilters();const visible=filteredResults();resultsGrid.replaceChildren();visible.forEach(result=>resultsGrid.appendChild(createCard(result)));resultCount.textContent=`${visible.length} / ${results.length}`;resultsTitle.textContent=favoritesOnly?"Favorites":"Everything worth keeping";emptyState.hidden=visible.length!==0;updateSummary()}
function createCard(result){const node=cardTemplate.content.cloneNode(true);node.querySelector(".category").textContent=result.category;node.querySelector(".title").textContent=result.title;node.querySelector(".summary").textContent=result.summary;const favoriteButton=node.querySelector(".favorite-button");favoriteButton.textContent=result.favorite?"★":"☆";favoriteButton.setAttribute("aria-pressed",String(Boolean(result.favorite)));favoriteButton.addEventListener("click",()=>toggleFavorite(result.id));const tags=node.querySelector(".tags");(result.tags||[]).forEach(tag=>{const item=document.createElement("span");item.className="tag";item.textContent=`#${tag}`;tags.appendChild(item)});node.querySelector(".open-button").addEventListener("click",()=>openResult(result.id));node.querySelector(".context-button").addEventListener("click",()=>openContext(result.id));return node}
function toggleFavorite(id){results=results.map(result=>result.id===id?{...result,favorite:!result.favorite}:result);saveResults();render()}
function openResult(id){const result=results.find(item=>item.id===id);if(!result)return;resultDialogContent.innerHTML="";const category=document.createElement("p");category.className="eyebrow";category.textContent=result.category;const title=document.createElement("h2");title.textContent=result.title;const summary=document.createElement("p");summary.className="muted";summary.textContent=result.summary;const details=document.createElement("div");details.className="detail-grid";details.appendChild(detailBlock("Decisions",(result.decisions||[]).join(" • ")||"No decisions captured yet."));details.appendChild(detailBlock("Next",result.next||"No next step captured yet."));const contextButton=document.createElement("button");contextButton.className="button primary";contextButton.textContent="Generate Context Pack";contextButton.addEventListener("click",()=>{resultDialog.close();openContext(id)});resultDialogContent.append(category,title,summary,details,contextButton);resultDialog.showModal()}
function detailBlock(label,value){const block=document.createElement("div");block.className="detail-block";const strong=document.createElement("strong");strong.textContent=label;const text=document.createElement("div");text.textContent=value;block.append(strong,text);return block}
function makeContextPack(result){return["# DashGPT Context Pack v0.1","",`TITLE: ${result.title}`,`CATEGORY: ${result.category}`,"","SUMMARY:",result.summary,"","DECISIONS:",...(result.decisions||[]).map(item=>`- ${item}`),"","TAGS:",(result.tags||[]).map(tag=>`#${tag}`).join(" ")||"none","","NEXT INTENDED ACTION:",result.next||"Not captured.","","CONTINUATION INSTRUCTION:","Continue from this state. Preserve the decisions above unless new evidence requires revisiting them."].join("\n")}
function openContext(id){const result=results.find(item=>item.id===id);if(!result)return;contextOutput.value=makeContextPack(result);contextDialog.showModal()}
async function copyContext(){try{await navigator.clipboard.writeText(contextOutput.value);const button=document.querySelector("#copyContextButton");button.textContent="Copied ✓";setTimeout(()=>button.textContent="Copy Context",1200)}catch{contextOutput.select();document.execCommand("copy")}}
function addResult(formData){const title=String(formData.get("title")||"").trim(),summary=String(formData.get("summary")||"").trim(),category=String(formData.get("category")||"Ideas").trim()||"Ideas",tags=String(formData.get("tags")||"").split(",").map(tag=>tag.trim()).filter(Boolean),next=String(formData.get("next")||"").trim();results.unshift({id:`${Date.now()}-${title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||"result"}`,title,summary,category,tags,favorite:false,decisions:[],next});saveResults();activeCategory="All";favoritesOnly=false;searchInput.value="";render()}
searchInput.addEventListener("input",render);document.querySelector("#showFavoritesButton").addEventListener("click",()=>{favoritesOnly=true;render()});document.querySelector("#showAllButton").addEventListener("click",()=>{favoritesOnly=false;render()});document.querySelector("#copyContextButton").addEventListener("click",copyContext);document.querySelector("#addResultButton").addEventListener("click",()=>addDialog.showModal());document.querySelector("#cancelAddButton").addEventListener("click",()=>addDialog.close());addResultForm.addEventListener("submit",event=>{event.preventDefault();addResult(new FormData(addResultForm));addResultForm.reset();addDialog.close()});render();
